name: Run API Aggregator

on:
  schedule:
    - cron: '8 0 * * *'  # 每天凌晨 00:00 UTC 运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史，避免 push 报错

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python main.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKENN }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Results
      run: |
        git add input.json output_base58.txt failed_apis.log github_sources.log
        git commit -m "🔄 自动更新 output.json 和日志文件"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
